name: Deploy SSIS Package
description: Deploys an SSIS package to SQL Server SSISDB or MSDB

inputs:
  sql_server_host:
    description: 'SQL Server hostname'
    required: true
  ispac_path:
    description: 'Path to the SSIS package (.dtsx or .ispac)'
    required: true
  catalog_path:
    description: 'SSISDB catalog path (e.g., SSISDB/ETL)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Deploy SSIS Package
      shell: powershell
      run: |
        $dtutilPath = "C:\Program Files\Microsoft SQL Server\160\DTS\Binn\dtutil.exe"
        if (-not (Test-Path $dtutilPath)) { throw "dtutil.exe not found. Ensure SSIS tools are installed." }

        $server = "${{ inputs.sql_server_host }}"
        $packagePath = "${{ inputs.ispac_path }}"
        $catalogPath = "${{ inputs.catalog_path }}"

        if (-not (Test-Path $packagePath)) { throw "SSIS package not found at $packagePath" }

        Write-Host "Deploying $packagePath to $server"

        if ($catalogPath) {
          # Deploy to SSISDB
          Write-Host "Deploying to SSISDB catalog: $catalogPath"
          & $dtutilPath /FILE "$packagePath" /COPY SQL;"$catalogPath" /DestServer $server
        } else {
          # Deploy to MSDB
          $msdbPath = [System.IO.Path]::GetFileNameWithoutExtension($packagePath)
          Write-Host "Deploying to MSDB as $msdbPath"
          & $dtutilPath /FILE "$packagePath" /COPY SQL;"$msdbPath" /DestServer $server
        }
