name: 'Deploy SSIS Project'
description: 'Deploys SSIS .ispac project to SQL Server Integration Services Catalog'

inputs:
  sql_server_host:
    description: 'SQL Server host'
    required: true
  ispac_path:
    description: 'Path to the .ispac file'
    required: true
  catalog_path:
    description: 'SSIS Catalog path, e.g., SSISDB/ETL'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy SSIS Project
      shell: powershell
      run: |
        $isDeploymentWizard = "C:\Program Files (x86)\Microsoft SQL Server\160\DAC\bin\ISDeploymentWizard.exe"  # Adjust version if needed
        if (-not (Test-Path $isDeploymentWizard)) { throw "ISDeploymentWizard.exe not found at $isDeploymentWizard. Ensure SQL Server Data Tools are installed." }
        
        $ispacPath = "${{ inputs.ispac_path }}"
        $server = "${{ inputs.sql_server_host }}"
        $catalogPath = "${{ inputs.catalog_path }}"

        if (-not (Test-Path $ispacPath)) { throw "ISPAC file not found at $ispacPath" }

        Write-Host "Deploying $ispacPath to $server in $catalogPath"

        & $isDeploymentWizard /Silent /SourcePath:$ispacPath /DestinationServer:$server /DestinationPath:"$catalogPath"
