
name: 'Deploy SSIS Packages'
description: 'Deploys SSIS packages to SQL Server using dtutil.exe'

inputs:
  sql_server_host:
    description: 'SQL Server host'
    required: true
  sql_user:
    description: 'SQL Server username'
    required: true
  sql_password:
    description: 'SQL Server password'
    required: true
  package_path:
    description: 'Path to the SSIS package (.dtsx) in the repository'
    required: true
  destination_path:
    description: 'Destination path in SSIS Catalog (e.g., /SSISDB/Folder/Package)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy SSIS Package
      shell: powershell
      run: |
        $dtutilPath = "C:\Program Files\Microsoft SQL Server\130\DTS\Binn\dtutil.exe"
        $env:Path += ";C:\Program Files\Microsoft SQL Server\130\DTS\Binn"
        & "$dtutilPath" /Copy SQL;"${{ inputs.destination_path }}" /DestServer "${{ inputs.sql_server_host }}" /DestUser "${{ inputs.sql_user }}" /DestPassword "${{ inputs.sql_password }}" /File "${{ inputs.package_path }}"
      env:
        SQLCMD: sqlcmd
