name: 'Deploy SSIS Packages'
description: 'Deploys SSIS packages to SQL Server using dtutil.exe with Windows Authentication'

inputs:
  sql_server_host:
    description: 'SQL Server host'
    required: true
  package_path:
    description: 'Path to the SSIS package (.dtsx) in the repository'
    required: true
  destination_path:
    description: 'Destination path in SSIS Catalog (e.g., /SSISDB/ETL/Projects)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy SSIS Package
      shell: powershell
      run: |
        $dtutilPath = "C:\Program Files\Microsoft SQL Server\160\DTS\Binn\dtutil.exe"  # Updated for SQL Server 2022
        $env:Path += ";C:\Program Files\Microsoft SQL Server\160\DTS\Binn"
        
        if (-not (Test-Path $dtutilPath)) { throw "dtutil.exe not found at $dtutilPath. Ensure SSIS for SQL Server 2022 is installed." }
        if (-not (Test-Path "${{ inputs.package_path }}")) { throw "SSIS package not found at ${{ inputs.package_path }}" }
        
        # Ensure the destination folder exists
        $folderPath = "${{ inputs.destination_path }}"
        $server = "${{ inputs.sql_server_host }}"
        $folderParts = $folderPath.Split('/')[2..($folderPath.Split('/').Length - 1)]  # Remove /SSISDB/ prefix
        $currentPath = "/SSISDB"
        foreach ($folder in $folderParts) {
          $currentPath += "/$folder"
          & $dtutilPath /SQL "$currentPath" /EXISTS /DestServer $server | Out-Null
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Creating folder $currentPath"
            & $dtutilPath /SQL "$currentPath" /FOLDER /CREATE /DestServer $server
          }
        }
        
        # Deploy the package
        & $dtutilPath /Copy "SQL;$folderPath" /DestServer $server /File "${{ inputs.package_path }}"
