name: Deploy SSIS Packages to SSISDB

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted
    environment: Dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy SSIS Package to SSISDB
        shell: powershell
        run: |
          $dtutilPath = "C:\Program Files\Microsoft SQL Server\160\DTS\Binn\dtutil.exe"
          if (-not (Test-Path $dtutilPath)) { throw "dtutil.exe not found. Ensure SSIS tools are installed." }

          $server = "${{ secrets.DEV_SQL_SERVER_HOST }}"
          $packagePath = "ssis/TimesheetFormStage.dtsx"
          $msdbPath = "MyDeployedPackage"  # Name to store package in MSDB

          if (-not (Test-Path $packagePath)) { throw "SSIS package not found at $packagePath" }

          Write-Host "Deploying $packagePath to SSISDB on $server as $msdbPath"

          & $dtutilPath /FILE "$packagePath" /COPY SQL;"$msdbPath" /DestServer $server
