name: 'Deploy SQL Scripts'
description: 'Deploys SQL scripts to a specified SQL Server'

inputs:
  environment:
    description: 'Target environment (e.g., Dev or Prod)'
    required: true
  sql_server_host:
    description: 'SQL Server host'
    required: true
  sql_user:
    description: 'SQL Server username'
    required: true
  sql_password:
    description: 'SQL Server password'
    required: true
  db_script:
    description: 'Path to the database creation script'
    required: false
    default: 'create_db_and_table.sql'
  proc_script:
    description: 'Path to the stored procedure script'
    required: false
    default: 'create_stored_procedure.sql'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run SQL Scripts
      shell: powershell
      run: |
        $env:Path += ";C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn"
        sqlcmd -S "${{ inputs.sql_server_host }}" -U "${{ inputs.sql_user }}" -P "${{ inputs.sql_password }}" -i "${{ inputs.db_script }}" -C
        sqlcmd -S "${{ inputs.sql_server_host }}" -U "${{ inputs.sql_user }}" -P "${{ inputs.sql_password }}" -i "${{ inputs.proc_script }}" -C
