name: Deploy SSIS Packages to SQL Server

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy-ssis:
    runs-on: self-hosted  # Make sure your runner has SSIS installed
    environment: Dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy SSIS Package
        uses: ./.github/actions/deploy-ssis
        with:
          sql_server_host: ${{ secrets.DEV_SQL_SERVER_HOST }}
          sql_user: ${{ secrets.DEV_SQL_USER }}
          sql_password: ${{ secrets.DEV_SQL_PASSWORD }}
          package_path: 'ssis/customer_import.dtsx'  # ✅ Update with actual file name
          destination_path: '/SSISDB/ETL/customer_import'  # ✅ Update with actual SSIS path

