name: Reusable SQL Deployment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment (e.g., Dev or Prod)'
        required: true
        type: string
      sql_server_host:
        description: 'SQL Server host'
        required: true
        type: string
      sql_user:
        description: 'SQL Server username'
        required: true
        type: string
      sql_password:
        description: 'SQL Server password'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}  # Set the environment dynamically
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SQLCMD
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg software-properties-common
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl -fsSL https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

      - name: Run SQL Scripts
        run: |
          export PATH="$PATH:/opt/mssql-tools/bin"
          sqlcmd -S "${{ inputs.sql_server_host }}" -U "${{ inputs.sql_user }}" -P "${{ inputs.sql_password }}" -i create_db_and_table.sql -C
          sqlcmd -S "${{ inputs.sql_server_host }}" -U "${{ inputs.sql_user }}" -P "${{ inputs.sql_password }}" -i create_stored_procedure.sql -C
