name: Deploy SSIS Packages to SQL Server

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted
    environment: Dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy SSIS Packages
        uses: ./.github/actions/deploy-ssis
        with:
          sql_server_host: 'localhost'
          package_path: 'ssis/TimesheetFormStage.dtsx'
          folder_name: 'ETL'
