name: Deploy SSIS Packages to SQL Server

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted
    environment: Dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy SSIS Project
        uses: ./.github/actions/deploy-ssis
        with:
          sql_server_host: ${{ secrets.DEV_SQL_SERVER_HOST }}
          ispac_path: 'ssis/bin/Development/ProjectSecondForLeave.ispac'
          catalog_path: 'SSISDB/ETL'
