name: Deploy AutoDBFirstName Database

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy-dev:
    runs-on: self-hosted  # Use self-hosted runner
    environment: Dev  # Development environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy SQL to Dev
        uses: ./.github/actions/testing
        with:
          environment: Dev
          sql_server_host: ${{ secrets.DEV_SQL_SERVER_HOST }}
          sql_user: ${{ secrets.DEV_SQL_USER }}
          sql_password: ${{ secrets.DEV_SQL_PASSWORD }}
          db_script: 'create_db_and_table.sql'
          proc_script: 'create_stored_procedure.sql'
