name: Deploy AutoDBFirstName Database

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy-dev:
    uses: ./.github/actions/testing # Call the reusable workflow
    with:
      environment: Dev
      sql_server_host: ${{ secrets.DEV_SQL_SERVER_HOST }}
      sql_user: ${{ secrets.DEV_SQL_USER }}
      sql_password: ${{ secrets.DEV_SQL_PASSWORD }}

  deploy-prod:
    needs: deploy-dev  # Runs after Dev deployment
    uses: ./.github/workflows/deploy-sql.yml  # Call the reusable workflow
    with:
      environment: Prod
      sql_server_host: ${{ secrets.PROD_SQL_SERVER_HOST }}
      sql_user: ${{ secrets.PROD_SQL_USER }}
      sql_password: ${{ secrets.PROD_SQL_PASSWORD }}
