name: Deploy SSIS Packages to SQL Server

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug workspace and user
        shell: powershell
        run: |
          Write-Output "Workspace path: ${{ github.workspace }}"
          Write-Output "Current user: $env:USERDOMAIN\$env:USERNAME"
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse

      - name: Verify SSIS project file exists
        shell: powershell
        run: |
          $projectPath = "${{ github.workspace }}\ssis"
          if (-not (Test-Path "$projectPath\ProjectSecondForLeave.dtproj")) {
            Write-Error "SSIS project file not found at: $projectPath"
            exit 1
          }
          Write-Output "Found SSIS project file at $projectPath"

      - name: Verify SSIS build tools exist
        shell: powershell
        run: |
          if (-not (Test-Path "C:\SSISDevOpsTools\SSISBuild.exe")) {
            Write-Error "SSISBuild.exe not found in C:\SSISDevOpsTools"
            exit 1
          }
          if (-not (Test-Path "C:\Program Files\Microsoft SQL Server\160\DTS\Binn\ISDeploymentWizard.exe")) {
            Write-Error "ISDeploymentWizard.exe not found"
            exit 1
          }
          if (-not (Get-Command sqlcmd.exe -ErrorAction SilentlyContinue)) {
            Write-Error "sqlcmd.exe not found"
            exit 1
          }
          Write-Output "All required tools found."

      - name: Copy Project.params to SSIS folder
        shell: powershell
        run: |
          Copy-Item "${{ github.workspace }}\Project.params" -Destination "${{ github.workspace }}\ssis\" -Force

      - name: Build SSIS Project
        shell: powershell
        run: |
          $projectFile = "${{ github.workspace }}\ssis\ProjectSecondForLeave.dtproj"
          $outputDir = "${{ runner.temp }}\SSISOutput"
          $config = "Development"
          if (-not (Test-Path $outputDir)) {
            New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
          }
          & "C:\SSISDevOpsTools\SSISBuild.exe" -p:"$projectFile" -o:"$outputDir" -c:"$config" -l:DIAG
          $ispacPath = Join-Path $outputDir "$config\ProjectSecondForLeave.ispac"
          if (-not (Test-Path $ispacPath)) {
            Wr
